---
abstract: 'Perl interface to the new StackExchange 2.1 API'
author:
  - 'Gideon Israel Dsouza <gideon@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-StackExchange2
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2.53
  LWP::UserAgent: 6.04
  Sub::Name: 0.05
  perl: 5.006
resources:
  repository: https://github.com/gideondsouza/perl-net-stackexchange/
version: 0.05
